export const MEDICAL_UNIVERSITIES = [
  "Acıbadem Mehmet Ali Aydınlar Üniversitesi",
  "Adıyaman Üniversitesi",
  "Adnan Menderes Üniversitesi",
  "Afyonkarahisar Sağlık Bilimleri Üniversitesi",
  "Ağrı İbrahim Çeçen Üniversitesi",
  "Akdeniz Üniversitesi",
  "Aksaray Üniversitesi",
  "Alanya Alaaddin Keykubat Üniversitesi",
  "Altınbaş Üniversitesi",
  "Amasya Üniversitesi",
  "Ankara Medipol Üniversitesi",
  "Ankara Üniversitesi",
  "Ankara Yıldırım Beyazıt Üniversitesi",
  "Atatürk Üniversitesi",
  "Atılım Üniversitesi",
  "Bahçeşehir Üniversitesi",
  "Balıkesir Üniversitesi",
  "Bandırma Onyedi Eylül Üniversitesi",
  "Başkent Üniversitesi",
  "Beykent Üniversitesi",
  "Bezm-i Âlem Vakıf Üniversitesi",
  "Biruni Üniversitesi",
  "Bolu Abant İzzet Baysal Üniversitesi",
  "Bursa Uludağ Üniversitesi",
  "Çanakkale Onsekiz Mart Üniversitesi",
  "Çukurova Üniversitesi",
  "Demiroğlu Bilim Üniversitesi",
  "Dicle Üniversitesi",
  "Dokuz Eylül Üniversitesi",
  "Düzce Üniversitesi",
  "Ege Üniversitesi",
  "Erciyes Üniversitesi",
  "Erzincan Binali Yıldırım Üniversitesi",
  "Eskişehir Osmangazi Üniversitesi",
  "Fırat Üniversitesi",
  "Gazi Üniversitesi",
  "Gaziantep İslam Bilim ve Teknoloji Üniversitesi",
  "Gaziantep Üniversitesi",
  "Giresun Üniversitesi",
  "Hacettepe Üniversitesi",
  "Haliç Üniversitesi",
  "Harran Üniversitesi",
  "Hatay Mustafa Kemal Üniversitesi",
  "Hitit Üniversitesi",
  "İnönü Üniversitesi",
  "İstanbul Arel Üniversitesi",
  "İstanbul Atlas Üniversitesi",
  "İstanbul Aydın Üniversitesi",
  "İstanbul Medeniyet Üniversitesi",
  "İstanbul Medipol Üniversitesi",
  "İstanbul Okan Üniversitesi",
  "İstanbul Sağlık ve Teknoloji Üniversitesi",
  "İstanbul Üniversitesi",
  "İstanbul Yeni Yüzyıl Üniversitesi",
  "İstinye Üniversitesi",
  "İzmir Bakırçay Üniversitesi",
  "İzmir Demokrasi Üniversitesi",
  "İzmir Ekonomi Üniversitesi",
  "İzmir Kâtip Çelebi Üniversitesi",
  "İzmir Tınaztepe Üniversitesi",
  "Kafkas Üniversitesi",
  "Kahramanmaraş Sütçü İmam Üniversitesi",
  "Karabük Üniversitesi",
  "Karadeniz Teknik Üniversitesi",
  "Karamanoğlu Mehmetbey Üniversitesi",
  "Kastamonu Üniversitesi",
  "Kırıkkale Üniversitesi",
  "Kırklareli Üniversitesi",
  "Kırşehir Ahi Evran Üniversitesi",
  "Kocaeli Üniversitesi",
  "Koç Üniversitesi",
  "KTO Karatay Üniversitesi",
  "Kütahya Sağlık Bilimleri Üniversitesi",
  "Lokman Hekim Üniversitesi",
  "Malatya Turgut Özal Üniversitesi",
  "Maltepe Üniversitesi",
  "Manisa Celal Bayar Üniversitesi",
  "Mardin Artuklu Üniversitesi",
  "Marmara Üniversitesi",
  "Mersin Üniversitesi",
  "Muğla Sıtkı Koçman Üniversitesi",
  "Necmettin Erbakan Üniversitesi",
  "Niğde Ömer Halisdemir Üniversitesi",
  "Nişantaşı Üniversitesi",
  "Ondokuz Mayıs Üniversitesi",
  "Ordu Üniversitesi",
  "Pamukkale Üniversitesi",
  "Recep Tayyip Erdoğan Üniversitesi",
  "Sağlık Bilimleri Üniversitesi",
  "Sakarya Üniversitesi",
  "Sanko Üniversitesi",
  "Selçuk Üniversitesi",
  "Siirt Üniversitesi",
  "Sivas Cumhuriyet Üniversitesi",
  "Süleyman Demirel Üniversitesi",
  "Tekirdağ Namık Kemal Üniversitesi",
  "TOBB Ekonomi ve Teknoloji Üniversitesi",
  "Tokat Gaziosmanpaşa Üniversitesi",
  "Trakya Üniversitesi",
  "Ufuk Üniversitesi",
  "Uşak Üniversitesi",
  "Üsküdar Üniversitesi",
  "Van Yüzüncü Yıl Üniversitesi",
  "Yalova Üniversitesi",
  "Yeditepe Üniversitesi",
  "Yozgat Bozok Üniversitesi",
  "Yüksek İhtisas Üniversitesi",
  "Zonguldak Bülent Ecevit Üniversitesi",
] as const;

export type MedicalUniversity = (typeof MEDICAL_UNIVERSITIES)[number];
